version: '3.9'

services:
  ## MySQL DB
  mysql:
    image: mysql:8.0.23
    restart: always
    volumes:
      - ./docker/database/:/var/lib/mysql/
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=petclinic
    healthcheck:
      test: [ "CMD", "mysql" ,"-h", "localhost", "-u", "petclinic", "--password=petclinic", "-e", "SELECT 1" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  # tracing
  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
      - 9411:9411

  ## Grafana / Prometheus
  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 3000:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 9091:9090
